### ISSUE TITLE
Weather: wunderground API no longer free/available for personal use

### ISSUE THREAD

**Issue by parkerbryan** [jlu5/SupyPlugins#71]
Current keys still work, though unsure for how much longer. If one wanted to pay for API access, their smallest package ("Core Data") according to a couple individuals who went through the process of filling out their form "For help finding the right data package for your business" were contacted and told $850/month.

**Comment by jlu5** [comment]
I'm aware :(

Really the solution at this point would be to write a new weather plugin using some other backend, preferably from scratch.
