### ISSUE TITLE
[idea] implement encryption

### ISSUE THREAD

**Issue by traumschule** [jlu5/SupyPlugins#73]
Sometimes it useful to encrypt conversations (for example in combination with #72) or queries.

- [Fishlim](/falsovsky/FiSH-irssi/issues/63)
- [OMEMO](https://omemo.top)
- [OTR](/cryptodotis/irssi-otr)

I wonder what you think about this or if there are better options.

**Comment by jlu5** [comment]
These are already open issues in Limnoria:
- OTR: https://github.com/ProgVal/Limnoria/issues/1214
- FiSH: https://github.com/ProgVal/Limnoria/issues/1137

So, closing as duplicate accordingly.
