### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by skeeloco** [jlu5/SupyPlugins#85]
<@skeeloco> .load Nuweather
<@Niska> skeeloco: Error: invalid syntax (plugin.py, line 244)

Also added # -*- coding: utf-8 -*- to the beginning as I was getting  Error: Non-ASCII character '\xc2'.

**Comment by jlu5** [comment]
Per the readme, Python 2 is not supported anymore. Please consider migrating to Python 3.

**Comment by skeeloco** [comment]
Oops didn't realize that, I got supybot using python3 it's working. Thanks a lot, I think this is the only working weather script out there since Wunderground started charging for their API!
