### ISSUE TITLE
NuWeather: Apixu is now Weatherstack

### ISSUE THREAD

**Issue by vectr0n** [jlu5/SupyPlugins#87]
Got an email today saying that Apixu is now Weatherstack. [https://github.com/apilayer/weatherstack#readme](https://github.com/apilayer/weatherstack#readme)

> Step 2: API Endpoints

> There are several API endpoints to choose from:

> Current Weather: Get current weather data.
> Historical Weather: Get historical weather data.
> Historical Time-Series: Get historical time-series weather data.
> Weather Forecast: Get weather forecast for up to 14 days.
> Location Lookup: Look up one or multiple locations.

> Base URL: API requests start out with the following base URL:
> http://api.weatherstack.com/

**Comment by jlu5** [comment]
Unfortunately it seems that extended forecasts are [no longer available for free](https://weatherstack.com/documentation), which really limits the usefulness of this backend...

I'm not sure how useful it'd be to only show current conditions using this backend. Any thoughts?
