### ISSUE TITLE
SedRegex: - Error: builtins.OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by TheDetectiveTaco** [jlu5/SupyPlugins#88]
When doing a correction with the SedRegex I get this error from the bot.

Error: builtins.OSError: [Errno 5] Input/output error

**Comment by jlu5** [comment]
Can you post the full traceback from messages.log or the console?

**Comment by TheDetectiveTaco** [comment]
`10-12T22:35:38 supybot SedRegex error: [Errno 5] Input/output e$Traceback (most recent call last): File "/home/D/DetectiveTaco/runbot/plugins/SedRegex/plugin.py", line 158, $ fcn_name='replacer'): File "/home/D/DetectiveTaco/.local/lib/python3.5/site-packages/supybot/com$ v = process(re_bool, s, reobj, timeout=timeout, pn=plugin_name, cn=fcn_n$ File "/home/D/DetectiveTaco/.local/lib/python3.5/site-packages/supybot/com$ p.start() File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start self._popen = self._Popen(self) File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen return Popen(process_obj) File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 17, in __ini$ sys.stdout.flush() OSError: [Errno 5] Input/output error [ Read 563 lines ]`

**Comment by jlu5** [comment]
This seems to be an upstream Python bug, see https://github.com/ProgVal/Limnoria/issues/1264

**Comment by jlu5** [comment]
(closing as duplicate)
