### ISSUE TITLE
SedRegex: not working

### ISSUE THREAD

**Issue by sacredland** [jlu5/SupyPlugins#91]
Bot joined #test 
<user> -config channel #test plugins.sedregex.enable True
<Bot> user: The operation succeeded.
<user>  tabb is cute
<user>  s/cute/ugly
<user>  helli world
<user>  s/i/o

..it is not working at all, or a miss something..

**Comment by jlu5** [comment]
You're missing the trailing slash in the expression. Use `s/cute/ugly/` instead of `s/cute/ugly` for example.

I'll see if there's a way of making the matching more flexible without causing side-effects like #59
